#!/usr/bin/env python
# -*- coding: utf-8 -*-


import os

import numpy as np
import rospy, roslaunch

from enum import Enum
from std_msgs.msg import UInt8, Float64


class ConstructionManager:
    def __init__(self):
        self.uuid = roslaunch.rlutil.get_or_generate_uuid(None, False)
        self.ros_package_path = os.path.dirname(os.path.realpath(__file__))
        self.ros_package_path = self.ros_package_path.replace('red_bucketoids_autorace_core/nodes', '')

        self.control_lane_is_move = rospy.Publisher('/control/lane/is_move', UInt8, queue_size=1)
        self.is_mission_over = rospy.Publisher('/mission/is_over', UInt8, queue_size=1)

        self.sub_is_construction = rospy.Subscriber('/detect/traffic_sign', UInt8, self.cbConstruction, queue_size=1)
        self.sub_construction_steps = rospy.Subscriber('/detect/construction_stamped', UInt8, self.cbConstructionExit, queue_size=1)

        rospy.loginfo("construction_manager - Start Construction Manager")
        self.initConstruction()


    def initConstruction(self):
        move_msg = UInt8()
        move_msg.data = 1
        self.control_lane_is_move.publish(move_msg)
        rospy.loginfo("construction_manager - Turn Up control_lane")

        roslaunch_file = self.ros_package_path + "red_bucketoids_autorace_detect/launch/detect_sign.launch"
        roslaunch_args = ["mission:=construction"]
        self.launch_construction_sign = roslaunch.parent.ROSLaunchParent(self.uuid, [(roslaunch_file, roslaunch_args)])
        self.launch_construction_sign.start()
        rospy.loginfo("construction_manager - Launch detect_construction_sign node")


    def cbConstruction(self, msg: UInt8):
        self.launch_construction_sign.shutdown()
        rospy.loginfo("construction_manager - Shutdown detect_construction_sign node")

        self.launch_construction = roslaunch.parent.ROSLaunchParent(self.uuid, [self.ros_package_path + "red_bucketoids_autorace_detect/launch/detect_construction.launch"])
        self.launch_construction.start()
        rospy.loginfo("construction_manager - Launch detect_construction node")


    def cbConstructionExit(self, msg: UInt8):
        self.launch_construction.shutdown()
        rospy.loginfo("construction_manager - Shutdown detect_construction node")

        move_msg = UInt8()
        move_msg.data = 1
        self.control_lane_is_move.publish(move_msg)
        rospy.loginfo("construction_manager -  Turn Up control_lane")

        rospy.loginfo("construction_manager - Send mission over message")
        mission_over = UInt8()
        mission_over.data = 1
        self.is_mission_over.publish(mission_over)


    def main(self):
        rospy.spin()


if __name__ == '__main__':
    rospy.init_node('construction_manager')
    node = ConstructionManager()
    node.main()
