#!/usr/bin/env python
# -*- coding: utf-8 -*-


import os

import numpy as np
import rospy, roslaunch

from enum import Enum
from std_msgs.msg import UInt8, Float64


class TrafficLightManager:
    def __init__(self):
        self.uuid = roslaunch.rlutil.get_or_generate_uuid(None, False)
        self.ros_package_path = os.path.dirname(os.path.realpath(__file__))
        self.ros_package_path = self.ros_package_path.replace('red_bucketoids_autorace_core/nodes', '')

        self.control_lane_is_move = rospy.Publisher('/control/lane/is_move', UInt8, queue_size=1)
        self.is_mission_over = rospy.Publisher('/mission/is_over', UInt8, queue_size=1)

        self.is_green_light = rospy.Subscriber('/detect/traffic_light', UInt8, self.cbGreenLight, queue_size=1)

        rospy.loginfo("traffic_light_manager - Start Traffic Light Manager")
        self.initTrafficLight()


    def initTrafficLight(self):
        not_move_msg = UInt8()
        not_move_msg.data = 0
        self.control_lane_is_move.publish(not_move_msg)
        rospy.loginfo("traffic_light_manager - Turn Off control_lane")

        self.launch_detect_traffic_light = roslaunch.parent.ROSLaunchParent(self.uuid, [self.ros_package_path + "red_bucketoids_autorace_detect/launch/detect_traffic_light.launch"])
        self.launch_detect_traffic_light.start()
        rospy.loginfo("traffic_light_manager - Launch detect_traffic_light node")


    def cbGreenLight(self, msg: UInt8):
        move_msg = UInt8()
        move_msg.data = 1
        self.control_lane_is_move.publish(move_msg)
        rospy.loginfo("traffic_light_manager -  Turn Up control_lane")

        self.launch_detect_traffic_light.shutdown()
        rospy.loginfo("traffic_light_manager - Shutdown detect_traffic_light node")

        mission_over = UInt8()
        mission_over.data = 1
        self.is_mission_over.publish(mission_over)
        rospy.loginfo("traffic_light_manager - Send mission over message")


    def main(self):
        rospy.spin()


if __name__ == '__main__':
    rospy.init_node('traffic_light_manager')
    node = TrafficLightManager()
    node.main()
